"""Patient-safe divergence screen for the retained four-qubit VQC.

This experiment changes only the VQC training objective.  Every candidate uses
the same fold-local Transformer->PLS q4 coordinates, patient-unique balanced
2,000-per-class sample, circuit, initialization, minibatch order and 30-epoch
budget.  Clinical teacher probabilities are generated by inner-fold OOF
prediction and then sigmoid-calibrated inside the outer training partition.
Folds 9 and 10 are rejected by the development access guard.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.special import expit, logit
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    brier_score_loss,
    log_loss,
    roc_auc_score,
)
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline

from aquire_preprocessing.config import DEV_FOLDS
from aquire_preprocessing.distillation import (
    FROZEN_DIVERGENCE_SCREEN,
    DistillationSpec,
    distillation_loss,
)
from aquire_preprocessing.feature_manifest import load_feature_manifest
from aquire_preprocessing.manifest import guard_fold_access
from aquire_preprocessing.models_quantum import TorchStatevectorQuantumClassifier
from run_advanced_quantum_fusion_screen import _fit_q4, _seed
from run_independent_dual_route_screen import _cross_fitted_fusion
from run_quantum_baselines import _paired_patient_bootstrap
from run_quantum_core_screen import _json_default, _patient_unique_sample


def _teacher_pipeline(seed: int):
    return make_pipeline(
        SimpleImputer(strategy="median", keep_empty_features=True),
        HistGradientBoostingClassifier(
            learning_rate=0.05,
            max_iter=180,
            max_leaf_nodes=15,
            min_samples_leaf=30,
            l2_regularization=1.0,
            random_state=int(seed),
        ),
    )


def _safe_logit(probability: np.ndarray) -> np.ndarray:
    return logit(np.clip(np.asarray(probability, dtype=float), 1e-5, 1.0 - 1e-5))


def _oof_calibrated_teacher(
    train_features: np.ndarray,
    train_labels: np.ndarray,
    train_folds: np.ndarray,
    val_features: np.ndarray,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, dict]:
    """Produce OOF soft targets and calibrated outer-validation predictions."""
    raw_oof_logits = np.full(len(train_labels), np.nan, dtype=float)
    unique_folds = sorted(np.unique(train_folds).astype(int))
    if len(unique_folds) < 3:
        raise ValueError("Teacher calibration requires at least three inner folds")
    for inner_fold in unique_folds:
        inner_val = train_folds == inner_fold
        inner_fit = ~inner_val
        if np.unique(train_labels[inner_fit]).size != 2:
            raise ValueError(f"Teacher inner fold {inner_fold} has one training class")
        teacher = _teacher_pipeline(seed + inner_fold)
        teacher.fit(train_features[inner_fit], train_labels[inner_fit])
        raw_oof_logits[inner_val] = _safe_logit(
            teacher.predict_proba(train_features[inner_val])[:, 1]
        )
    if not np.isfinite(raw_oof_logits).all():
        raise RuntimeError("Incomplete teacher inner-OOF predictions")

    # A two-parameter sigmoid calibrator is fit only on outer-training OOF
    # predictions.  Outer-validation labels never influence the soft targets.
    calibrator = LogisticRegression(C=1.0, solver="lbfgs", max_iter=1000)
    calibrator.fit(raw_oof_logits.reshape(-1, 1), train_labels)
    train_probability = calibrator.predict_proba(raw_oof_logits.reshape(-1, 1))[:, 1]

    full_teacher = _teacher_pipeline(seed)
    full_teacher.fit(train_features, train_labels)
    val_raw_logits = _safe_logit(full_teacher.predict_proba(val_features)[:, 1])
    val_probability = calibrator.predict_proba(val_raw_logits.reshape(-1, 1))[:, 1]
    if not np.isfinite(train_probability).all() or not np.isfinite(val_probability).all():
        raise RuntimeError("Non-finite calibrated teacher probability")
    audit = {
        "inner_folds": unique_folds,
        "oof_auprc_raw": float(average_precision_score(train_labels, expit(raw_oof_logits))),
        "oof_auprc_calibrated": float(average_precision_score(train_labels, train_probability)),
        "oof_brier_raw": float(brier_score_loss(train_labels, expit(raw_oof_logits))),
        "oof_brier_calibrated": float(brier_score_loss(train_labels, train_probability)),
        "calibration_intercept": float(calibrator.intercept_[0]),
        "calibration_slope": float(calibrator.coef_[0, 0]),
        "probability_min": float(train_probability.min()),
        "probability_max": float(train_probability.max()),
    }
    return train_probability.astype(np.float32), val_probability.astype(np.float32), audit


def _train_candidate(
    train_q: np.ndarray,
    train_y: np.ndarray,
    teacher_probability: np.ndarray,
    val_q: np.ndarray,
    spec: DistillationSpec,
    *,
    epochs: int,
    batch_size: int,
    seed: int,
    device,
) -> tuple[np.ndarray, dict]:
    import torch

    _seed(seed)
    model = TorchStatevectorQuantumClassifier(4, n_layers=2, topology="ring").to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=5e-3, weight_decay=1e-4)
    x = torch.from_numpy(train_q).to(device)
    y = torch.from_numpy(train_y.astype(np.float32)).to(device)
    teacher = torch.from_numpy(teacher_probability.astype(np.float32)).to(device)
    indices = np.arange(len(train_q))
    rng = np.random.default_rng(seed)
    losses, gradient_norms = [], []
    for _ in range(epochs):
        rng.shuffle(indices)
        running, seen, epoch_gradients = 0.0, 0, []
        model.train()
        for start in range(0, len(indices), batch_size):
            batch = indices[start : start + batch_size]
            optimizer.zero_grad(set_to_none=True)
            loss = distillation_loss(model(x[batch]), y[batch], teacher[batch], spec)
            loss.backward()
            gradient = torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            running += float(loss.detach()) * len(batch)
            seen += len(batch)
            epoch_gradients.append(float(gradient))
        losses.append(running / max(seen, 1))
        gradient_norms.append(float(np.median(epoch_gradients)))
    model.eval()
    with torch.inference_mode():
        logits = model(torch.from_numpy(val_q).to(device)).cpu().numpy()
    if not np.isfinite(logits).all():
        raise RuntimeError(f"Non-finite VQC output for {spec.name}")
    return logits, {
        "spec": spec.to_dict(),
        "parameters": int(sum(parameter.numel() for parameter in model.parameters())),
        "initial_loss": float(losses[0]),
        "final_loss": float(losses[-1]),
        "loss_declined": bool(losses[-1] < losses[0]),
        "gradient_norm_min": float(np.min(gradient_norms)),
        "gradient_norm_max": float(np.max(gradient_norms)),
        "epochs": int(epochs),
        "simulator": "exact_torch_statevector",
        "device": str(device),
    }


def _metrics(labels: np.ndarray, probability: np.ndarray) -> dict:
    probability = np.clip(np.asarray(probability, dtype=float), 1e-7, 1.0 - 1e-7)
    bins = np.linspace(0.0, 1.0, 11)
    ece = 0.0
    for lower, upper in zip(bins[:-1], bins[1:]):
        selected = (probability >= lower) & (
            probability <= upper if upper == 1.0 else probability < upper
        )
        if selected.any():
            ece += selected.mean() * abs(
                probability[selected].mean() - labels[selected].mean()
            )
    return {
        "auprc": float(average_precision_score(labels, probability)),
        "auroc": float(roc_auc_score(labels, probability)),
        "brier": float(brier_score_loss(labels, probability)),
        "logloss": float(log_loss(labels, probability)),
        "ece10": float(ece),
    }


def _validate_representations(representations: Path, joined: pd.DataFrame) -> dict[int, Path]:
    folds = joined.strat_fold.to_numpy(int)
    record_ids = joined.index.to_numpy(int)
    patients = joined.patient_id.to_numpy(int)
    paths, validation_ids = {}, []
    for held_out in sorted(np.unique(folds).astype(int)):
        path = representations / f"outer_fold_{held_out}_representations.npz"
        if not path.exists():
            raise FileNotFoundError(path)
        with np.load(path, allow_pickle=False) as rep:
            required = {
                "train_record_ids", "val_record_ids", "train_patient_ids",
                "val_patient_ids", "train_labels", "val_labels",
                "train_embeddings", "val_embeddings",
            }
            missing = required - set(rep.files)
            if missing:
                raise KeyError(f"{path.name} missing {sorted(missing)}")
            train_ids = rep["train_record_ids"].astype(int)
            val_ids = rep["val_record_ids"].astype(int)
            if set(train_ids) != set(record_ids[folds != held_out]):
                raise ValueError(f"Fold {held_out} training IDs disagree with metadata")
            if set(val_ids) != set(record_ids[folds == held_out]):
                raise ValueError(f"Fold {held_out} validation IDs disagree with metadata")
            if set(rep["train_patient_ids"].astype(int)) & set(rep["val_patient_ids"].astype(int)):
                raise ValueError(f"Patient leakage in Transformer fold {held_out}")
            if rep["train_embeddings"].shape != (len(train_ids), 128):
                raise ValueError(f"Unexpected train representation shape in fold {held_out}")
            if rep["val_embeddings"].shape != (len(val_ids), 128):
                raise ValueError(f"Unexpected validation representation shape in fold {held_out}")
            validation_ids.extend(val_ids.tolist())
        paths[held_out] = path
    if len(validation_ids) != len(set(validation_ids)) or set(validation_ids) != set(record_ids):
        raise ValueError("Transformer validation coverage is incomplete or duplicated")
    if joined.groupby("patient_id").strat_fold.nunique().max() != 1:
        raise ValueError("Patient crosses development folds")
    return paths


def run(args) -> None:
    import torch

    args.output.mkdir(parents=True, exist_ok=True)
    metadata = pd.read_csv(args.metadata).set_index("ecg_id")
    feature_frame = pd.read_csv(args.features).set_index("ecg_id")
    manifest = load_feature_manifest(args.manifest, feature_frame.columns)
    approved = manifest["approved_features"]
    joined = metadata.join(feature_frame[approved], how="inner", validate="one_to_one")
    joined = joined[
        joined.strat_fold.isin(DEV_FOLDS) & joined.eligibility.eq("PRIMARY")
    ].copy()
    folds = joined.strat_fold.to_numpy(int)
    guard_fold_access(folds, purpose="tuning")
    labels = joined.mi_label.to_numpy(int)
    patients = joined.patient_id.to_numpy(int)
    hard = joined.hard_negative.to_numpy(bool)
    record_ids = joined.index.to_numpy(int)
    clinical = joined[approved].to_numpy(np.float32)
    row_for_id = {int(ecg_id): row for row, ecg_id in enumerate(record_ids)}
    representation_paths = _validate_representations(args.representations, joined)
    preflight = {
        "records": int(len(joined)), "patients": int(joined.patient_id.nunique()),
        "approved_features": int(len(approved)),
        "folds": sorted(np.unique(folds).astype(int).tolist()),
        "representations": int(len(representation_paths)),
        "fold_9_accessed": False, "fold_10_accessed": False,
    }
    (args.output / "preflight.json").write_text(json.dumps(preflight, indent=2))
    if args.preflight_only:
        print(json.dumps(preflight, indent=2), flush=True)
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    spec_by_name = {spec.name: spec for spec in FROZEN_DIVERGENCE_SCREEN}
    prediction_names = [f"vqc_{name}" for name in spec_by_name]
    predictions = {
        name: np.full(len(joined), np.nan, dtype=float)
        for name in prediction_names + ["clinical_teacher", "q4_logistic", "q4_mlp"]
    }
    teacher_audits, quantum_audits = [], []

    for held_out in sorted(np.unique(folds).astype(int)):
        print(f"fold {held_out}", flush=True)
        with np.load(representation_paths[held_out], allow_pickle=False) as rep:
            train_ids = rep["train_record_ids"].astype(int)
            val_ids = rep["val_record_ids"].astype(int)
            train_h = rep["train_embeddings"].astype(np.float32)
            val_h = rep["val_embeddings"].astype(np.float32)
            train_y = rep["train_labels"].astype(int)
            train_patients = rep["train_patient_ids"].astype(int)
        train_rows = np.asarray([row_for_id[int(ecg_id)] for ecg_id in train_ids])
        val_rows = np.asarray([row_for_id[int(ecg_id)] for ecg_id in val_ids])
        if not np.array_equal(train_y, labels[train_rows]):
            raise ValueError(f"Fold {held_out} label alignment failed")
        train_q, val_q, correlations = _fit_q4(
            train_h, train_y, val_h, args.seed + held_out
        )
        teacher_train, teacher_val, teacher_audit = _oof_calibrated_teacher(
            clinical[train_rows], train_y, folds[train_rows], clinical[val_rows],
            args.seed + held_out * 10,
        )
        predictions["clinical_teacher"][val_rows] = teacher_val
        teacher_audits.append({"fold": held_out, **teacher_audit})
        sample = _patient_unique_sample(
            train_y, hard[train_rows], train_patients,
            per_class=args.per_class, seed=args.seed + held_out,
        )
        q_sample = train_q[sample]
        y_sample = train_y[sample]
        teacher_sample = teacher_train[sample]
        for name, spec in spec_by_name.items():
            logits, audit = _train_candidate(
                q_sample, y_sample, teacher_sample, val_q, spec,
                epochs=args.epochs, batch_size=args.batch_size,
                seed=args.seed + held_out * 100, device=device,
            )
            predictions[f"vqc_{name}"][val_rows] = expit(logits)
            quantum_audits.append({
                "fold": held_out, "q4_label_correlations": correlations, **audit,
            })
            print(
                f"  {name}: {average_precision_score(labels[val_rows], expit(logits)):.4f}",
                flush=True,
            )

        logistic = LogisticRegression(C=1.0, class_weight="balanced", max_iter=2000)
        logistic.fit(q_sample, y_sample)
        predictions["q4_logistic"][val_rows] = logistic.predict_proba(val_q)[:, 1]
        mlp = MLPClassifier(
            hidden_layer_sizes=(7,), max_iter=500,
            random_state=args.seed + held_out * 100 + 1,
        )
        mlp.fit(q_sample, y_sample)
        predictions["q4_mlp"][val_rows] = mlp.predict_proba(val_q)[:, 1]

    if any(not np.isfinite(value).all() for value in predictions.values()):
        raise RuntimeError("Incomplete OOF predictions")
    fusion_predictions = {}
    clinical_logit = _safe_logit(predictions["clinical_teacher"])
    for name in spec_by_name:
        fused_logit, _ = _cross_fitted_fusion(
            clinical_logit, _safe_logit(predictions[f"vqc_{name}"]), labels, folds
        )
        fusion_predictions[f"fusion_{name}"] = expit(fused_logit)
    classical_fusion_logit, classical_fusion_coefficients = _cross_fitted_fusion(
        clinical_logit, _safe_logit(predictions["q4_mlp"]), labels, folds
    )
    fusion_predictions["fusion_q4_mlp"] = expit(classical_fusion_logit)

    all_predictions = {**predictions, **fusion_predictions}
    metrics = {name: _metrics(labels, value) for name, value in all_predictions.items()}
    comparisons = {}
    hard_probability = predictions["vqc_hard"]
    for name in spec_by_name:
        if name == "hard":
            continue
        for control_name, control_probability in (
            ("hard", hard_probability),
            ("q4_logistic", predictions["q4_logistic"]),
            ("q4_mlp", predictions["q4_mlp"]),
        ):
            key = f"vqc_{name}_minus_{control_name}"
            comparisons[key] = _paired_patient_bootstrap(
                labels, patients, predictions[f"vqc_{name}"], control_probability,
                iterations=args.bootstrap_iterations, seed=args.seed,
                comparison=key,
            )
        key = f"fusion_{name}_minus_fusion_q4_mlp"
        comparisons[key] = _paired_patient_bootstrap(
            labels, patients, fusion_predictions[f"fusion_{name}"],
            fusion_predictions["fusion_q4_mlp"],
            iterations=args.bootstrap_iterations, seed=args.seed,
            comparison=key,
        )

    candidate_names = [name for name in spec_by_name if name != "hard"]
    winner = max(
        candidate_names,
        key=lambda name: (metrics[f"vqc_{name}"]["auprc"], -metrics[f"vqc_{name}"]["brier"]),
    )
    versus_hard = comparisons[f"vqc_{winner}_minus_hard"]["delta_auprc"]
    best_control = max(
        ("q4_logistic", "q4_mlp"), key=lambda name: metrics[name]["auprc"]
    )
    versus_control = comparisons[f"vqc_{winner}_minus_{best_control}"]["delta_auprc"]
    verdict = {
        "screen_winner": winner,
        "winner_auprc": metrics[f"vqc_{winner}"]["auprc"],
        "hard_control_auprc": metrics["vqc_hard"]["auprc"],
        "best_identical_q4_control": best_control,
        "best_identical_q4_control_auprc": metrics[best_control]["auprc"],
        "advance_to_five_seeds": bool(
            metrics[f"vqc_{winner}"]["auprc"] - metrics["vqc_hard"]["auprc"] >= 0.005
            and versus_hard["ci95_low"] > 0.0
        ),
        "quantum_predictive_advantage_gate": bool(versus_control["ci95_low"] > 0.0),
        "claim_boundary": (
            "A divergence screen can establish improved VQC training, not computational "
            "quantum advantage. Five prespecified seeds are required before promotion."
        ),
        "fold_9_accessed": False, "fold_10_accessed": False,
    }

    pd.DataFrame({
        "ecg_id": record_ids, "patient_id": patients, "strat_fold": folds,
        "y_true": labels, **all_predictions,
    }).to_csv(args.output / "oof_predictions.csv", index=False)
    pd.DataFrame([
        {"model": name, **values} for name, values in metrics.items()
    ]).sort_values("auprc", ascending=False).to_csv(args.output / "metrics.csv", index=False)
    (args.output / "teacher_audits.json").write_text(
        json.dumps(teacher_audits, indent=2, default=_json_default)
    )
    (args.output / "quantum_audits.json").write_text(
        json.dumps(quantum_audits, indent=2, default=_json_default)
    )
    (args.output / "bootstrap.json").write_text(
        json.dumps(comparisons, indent=2, default=_json_default)
    )
    (args.output / "classical_fusion_coefficients.json").write_text(
        json.dumps(classical_fusion_coefficients, indent=2, default=_json_default)
    )
    (args.output / "experiment_config.json").write_text(json.dumps({
        "specs": [spec.to_dict() for spec in FROZEN_DIVERGENCE_SCREEN],
        "per_class": args.per_class, "epochs": args.epochs,
        "batch_size": args.batch_size, "seed": args.seed,
        "teacher": "inner-fold OOF HistGB plus outer-training sigmoid calibration",
    }, indent=2))
    (args.output / "verdict.json").write_text(json.dumps(verdict, indent=2))
    print(json.dumps({"metrics": metrics, "verdict": verdict}, indent=2), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--representations", type=Path, required=True)
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--features", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--per-class", type=int, default=2000)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--bootstrap-iterations", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=20260925)
    parser.add_argument("--preflight-only", action="store_true")
    run(parser.parse_args())


if __name__ == "__main__":
    main()
